id: PCE3AEEDF
initial_creation_type: input
source_metadata:
  title: The Lamdre teaching record by Phags pa blo gros rgyal mtshan (1235–1280)
  author: འཕགས་པ་བློ་གྲོས་རྒྱལ་མཚན།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2020-06-19);
    no thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།; This text was published by the Paltsek Research
    Institute. (src)
  - Text input:དཔལ་བརྩེགས་བོད་ཡིག་དཔེ་རྙིང་ཞིབ་འཇུག་ཁང་། (Lhasa) (eds)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/4285
  bases:
    eea8:
      title: The Lamdre teaching record by Phags pa blo gros rgyal mtshan (1235–1280)
      order: 1
      base_file: eea8.txt
created_at: '2022-04-15T18:46:39.568677'
last_modified_at: '2022-04-15T18:46:39.568684'
quality: null
